name: abd_petcare
description: Application mobile ABD PetCare (Android/iOS, Web optionnel)
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  go_router: ^14.2.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  form_validator: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


