include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: false
    cascade_invocations: false


